import style from 'provider/style';

const styles = (theme: any) => ({
    root: {
        width: "100%",
        position: "relative",
        overflow: "hidden",
        borderRadius: 8,
        backgroundColor: theme.palette.primary,
        border: `1px solid ${theme.palette.primary}`,
        boxShadow: "0px 10px 20px -5px rgba(68, 74, 81, 0.1)",
      },
      extraColumns: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        borderBottom: "1px solid #e2e6e9",
        position: "relative",
      },
      titleBar: {
        whiteSpace: "nowrap",
        width: "100%",
        height: 40,
        position: "relative",
        background: theme.palette.primary,
        color: "white",
      },
      descriptionBar: {
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        whiteSpace: "nowrap",
        width: "100%",
        height: 40,
        position: "relative",
        background: theme.palette.secondary,
        color: "white",
      },
      title: {
        whiteSpace: "nowrap",
        height: "100%",
        display: "flex",
        alignItems: "center",
        padding: "0 60px",
        color: "white",
        fontStyle: "normal",
        fontWeight: 900,
        fontSize: 16,
        letterSpacing: "-0.01em,",
      },
      descriptions: {
        whiteSpace: "nowrap",
        height: "100%",
        width: "100%",
        display: "flex",
        alignItems: "center",
        padding: "0 60px",
        color: "white",
        fontStyle: "normal",
        fontWeight: 900,
        fontSize: 16,
        letterSpacing: "-0.01em",
        "& span": {
          cursor: "pointer",
        },
      },
      spinner: {
        position: "absolute",
        width: "100%",
        height: "100%",
        margin: "auto",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1,
        "&:after": {
          zIndex: -1,
          content: "''",
          left: 0,
          top: 0,
          opacity: 0.8,
          right: 0,
          bottom: 10,
          position: "absolute",
          width: "100%",
          background: "white",
          height: "100%",
        },
      },
      ringtext: {
        color: "white",
        minWidth: 150,
        fontSize: 14,
        fontWeight: 500,
      },
      activeringtext: {
        color: "white",
        minWidth: 150,
        fontSize: 16,
        fontWeight: 900,
      },
      wrapper: {
        display: "flex",
        alignItems: "center",
        flexDirection: "column",
        width: "100%",
        position: "relative",
        overflowY: "auto",
        maxHeight: 500,
        backgroundColor: theme.palette.white,
        /* width */
        "&::-webkit-scrollbar": {
          width: 5,
          backgroundColor: "white",
        },
    
        /* Track */
        "&::-webkit-scrollbar-track": {
          boxShadow: `inset 0 0 1px ${theme.palette.primary}`,
          borderRadius: 10,
          width: 1,
        },
    
        /* Handle */
        "&::-webkit-scrollbar-thumb": {
          background: "rgba(12, 14, 60, 0.2)",
          borderRadius: 10,
          width: 1,
        },
      },
      header: {
        width: "100%",
        height: 45,
        backgroundColor: theme.palette.primary,
        color: "white",
        display: "flex",
        alignItems: "center",
        position: "sticky",
        top: 0,
    
      },
      headerItem: {
        height: 45,
        backgroundColor: theme.palette.primary,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "white",
        width: "100%",
        textAlign: "center",
        minWidth: 100,
        fontWeight: "bold",
        fontSize: 14,
        position: "relative",
      },
      listItems: {
        position: "relative",
        width: "100%",
        display: "flex",
        "&:nth-child(2n)": {
          backgroundColor: theme.palette.colors[500],
        },
        "&:not(:last-child)": {
          "&:after": {
            width: "100%",
            content: "''",
            // borderBottom: "1px solid #e2e6e9",
            position: "absolute",
            bottom: 0,
          },
        },
      },
      items: {
        backgroundColor: "transparent",
        minWidth: 100,
        overflow: "hidden",
        width: "100%",
        padding: "0 15px",
        display: "flex",
        alignItems: "center",
        textAlign: "center",
        justifyContent: "center",
        minHeight: 50,
        position: "relative",
      },
      showmoreItem: {
        backgroundColor: "transparent",
        minWidth: 50,
        overflow: "hidden",
        padding: 0,
        display: "flex",
        alignItems: "center",
        textAlign: "center",
        justifyContent: "center",
        minHeight: 45,
        position: "relative",
        cursor: "pointer",
      },
      showmoreColumn: {
        backgroundColor: theme.palette.primary,
        minWidth: 50,
        overflow: "hidden",
        padding: 0,
        display: "flex",
        alignItems: "center",
        textAlign: "center",
        justifyContent: "center",
        minHeight: 45,
        position: "relative",
      },
      itemprecent: {
        display: "flex",
        alignItems: "center",
      },
      showmore: {
        width: 24,
        height: 24,
        backgroundColor: theme.palette.primary,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "& span ": {
          fontSize: 17,
          color: "white",
        },
      },
      value: {
        width: 60,
        fontSize: 16,
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.53,
        letterSpacing: -0.6,
        textAlign: "revert",
        color: theme.palette.black,
      },
      precent: {
        direction: "ltr",
        width: 40,
        margin: "0 10px",
        fontSize: 15,
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.53,
        letterSpacing: -0.6,
        textAlign: "right",
        color: theme.palette.primary,
      },
      moreLinks: {
        flexWrap: "wrap",
        position: "relative",
        width: "100%",
        display: "flex",
        gridGap: "5px 30px",
        overflow: "hidden",
        backgroundColor: theme.palette.third,
        "&:not(:last-child)": {
          "&:after": {
            width: "100%",
            content: "''",
            borderBottom: `1px solid ${theme.palette.colors.secondary}`,
            position: "absolute",
            bottom: 0,
          },
        },
      },
      emptyTable: {
        backgroundColor: "white",
        width: "100%",
        height: 265,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        "& i": {
          fontSize: 130,
          color: theme.palette.primary,
        },
        "& span": {
          fontStyle: "normal",
          fontWeight: 900,
          fontSize: 16,
          textAlign: "center",
          letterSpacing: "-0.01em",
          color: theme.palette.primary,
          lineHeight: 2.5,
        },
        "& small": {
          fontStyle: "normal",
          fontWeight: "normal",
          fontSize: 16,
          textAlign: "center",
          letterSpacing: "-0.01em",
          color: theme.palette.primary,
        },
      },
      moreLinksItem: {
        height: 45,
        padding: "0 20px",
        backgroundColor: theme.palette.third,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "black",
        textAlign: "center",
        minWidth: 100,
        fontWeight: "bold",
        fontSize: 14,
        position: "relative",
        whiteSpace: "nowrap",
      },
      name: {
        fontStyle: "normal",
        fontWeight: "normal",
        fontSize: 14,
        color: theme.palette.primary,
      },
      "@media screen and (max-width: 1000px)": {
        value: {
            fontStyle: "normal",
            fontWeight: 500,
            fontSize: 14,
            margin: "0 5px",
          },
        items: {
          overflow: "hidden",
          width: "100%",
          padding: "0px",
        },
        emptyTable: {
          "& i": {
            fontSize: 100,
          },
          "& span": {
            fontSize: 14,
          },
          "& small": {
            fontSize: 14,
          },
        },
      },
      "@media screen and (max-width: 700px)": {
        title: {
          backgroundColor: "black",
          width: "100% !important",
          justifyContent: "flex-start",
          whiteSpace: "normal",
          lineHeight: 1.7,
          padding: "0 20px",
          minHeight: 40,
        },
        moreLinks: {
          gridGap: 0,
        },
        titleBar: {
          height: "auto",
          minHeight: 40,
        },
      },
    
});

export default style(styles);
